# Basic Crowdin CLI configuration
# See https://crowdin.github.io/crowdin-cli/configuration for more information
# See https://support.crowdin.com/developer/configuration-file/ for all available options

project_id: '822500'
base_path: ./src
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: /locales/en.json
    translation: '/locales/%two_letters_code%.json'
