services:
  ptoj-db:
    image: mongo:latest
    container_name: ptoj-db
    restart: always
    volumes:
      - ./resource/db:/data/db
      - ./resource/backup:/data/backup
    networks:
      - ptoj
    profiles:
      - prod
  
  ptoj-db-dev:
    image: mongo:latest
    container_name: ptoj-db
    restart: always
    volumes:
      - ./resource/db:/data/db
      - ./resource/backup:/data/backup
    ports:
      - 27017:27017
    networks:
      - ptoj
    profiles:
      - dev

  ptoj-redis:
    image: redis:latest
    container_name: ptoj-redis
    restart: always
    volumes:
      - ./resource/cache:/data
    networks:
      - ptoj
    profiles:
      - prod

  ptoj-redis-dev:
    image: redis:latest
    container_name: ptoj-redis
    restart: always
    volumes:
      - ./resource/cache:/data
    ports:
      - 6379:6379
    networks:
      - ptoj
    profiles:
      - dev

  ptoj-app:
    container_name: ptoj-app
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - NODE_ENV=production
      - dbURL=mongodb://ptoj-db:27017/oj
      - redisURL=redis://ptoj-redis:6379
    ports:
      - '0.0.0.0:3000:3000'
    volumes:
      - ./resource/data:/app/data
      - ./resource/logs:/app/logs
    depends_on:
      - ptoj-redis
      - ptoj-db
    restart: always
    networks:
      - ptoj
    profiles:
      - prod

  ptoj-judger:
    container_name: ptoj-judger
    build:
      context: .
      dockerfile: judger.dockerfile
    environment:
      - NODE_ENV=production
      - dbURL=mongodb://ptoj-db:27017/oj
      - redisURL=redis://ptoj-redis:6379
    volumes:
      - ./resource/data:/app/data
      - ./resource/logs:/app/logs
    depends_on:
      - ptoj-app
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - ptoj
    profiles:
      - prod
  
  ptoj-judger-dev:
    container_name: ptoj-judger
    build:
      context: .
      dockerfile: judger.dockerfile
    environment:
      - NODE_ENV=development
      - dbURL=mongodb://ptoj-db-dev:27017/oj
      - redisURL=redis://ptoj-redis-dev:6379
    volumes:
      - ./resource/data:/app/data
      - ./resource/logs:/app/logs
    depends_on:
      - ptoj-db-dev
      - ptoj-redis-dev
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - ptoj
    profiles:
      - dev

networks:
  ptoj:
    driver: bridge
